[rewrite_local]
^https:\/\/config-home\.opayweb\.com\/version\/check url script-request-body https://raw.githubusercontent.com/TonyTeo98/NigeriaCash/main/opay/opay_version.js
^https:\/\/api\.opayweb\.com\/api\/validationPool\/v2\/validation$ url script-request-body https://raw.githubusercontent.com/TonyTeo98/NigeriaCash/main/opay/face_opay.js

[mitm]
hostname = config-home.opayweb.com, api.opayweb.com
